

DEBUG = True
SQLALCHEMY_ECHO = True
JSON_AS_ASCII = False
SQLALCHEMY_DATABASE_URI = 'mysql://root:491001@127.0.0.1/Courier'
SERVER_PORT = 8888
SQLALCHEMY_TRACK_MODIFICATIONS = True
SQLALCHEMY_ENCODING = "utf8mb4"

from flask import config